### ISSUE TITLE
SDL_SetWindowFullscreen is not supported

### ISSUE THREAD

**Issue by jfcalvo** [crimsonwoods/mruby-sdl2#6]
Any reason why [`SDL_SetWindowFullscreen`](https://wiki.libsdl.org/SDL_SetWindowFullscreen) is not supported?

**Comment by crimsonwoods** [comment]
I have no reason. Maybe, I forgot or overlooked.

**Comment by jfcalvo** [comment]
Ok, I can make a PR.

**Comment by jfcalvo** [comment]
Closing, it was solved by https://github.com/crimsonwoods/mruby-sdl2/pull/7
